In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle #Pickle is specifically for pickling because when we are using the standard scaler and label encoder we are going to use pickle to save the model and load it when we need it.

In [5]:
#Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
##Preprocessing the data
data.drop(["RowNumber","CustomerId","Surname"], axis=1, inplace=True) #inplace=True means that we are going to drop the columns from the original dataset and not create a new dataset.,axis=1 means that we are going to drop the columns and not the rows.
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
#Encode Categorical Data
label_encoder_gender = LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"]) #fit_transorm is used to fit the label encoder and transform the data at the same time.

In [8]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [9]:
#One Hot Encode:Geography as it has more than 2 categories and if we did it like label encoding, it would introduce a false ordinal relationship between the categories. So we will use one hot encoding to create dummy variables for each category.
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()

In [10]:
geo_encoder = onehot_encoder.fit_transform(data[["Geography"]]).toarray() #fit_transform is used to fit the one hot encoder and transform the data at the same time. toarray() is used to convert the sparse matrix to a dense matrix.

In [11]:
geo_encoder.shape

(10000, 3)

In [12]:
onehot_encoder.get_feature_names_out(["Geography"]) #get_feature_names_out() is used to get the feature names of the one hot encoder. It will return an array of feature names.

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=onehot_encoder.get_feature_names_out(["Geography"])) #We are creating a new dataframe with the one hot encoded data and the feature names as the column names.

In [14]:
data = pd.concat([data.drop(["Geography"],axis=1,inplace=False),geo_encoded_df],axis=1) #We are concatenating the original dataframe with the one hot encoded dataframe. We are dropping the original "Geography" column from the original dataframe and concatenating it with the one hot encoded dataframe. axis=1 means that we are concatenating the dataframes horizontally.
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [15]:
#Save the encoders and labels using pickle
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder.pkl','wb') as file:
    pickle.dump(onehot_encoder,file)
#

In [16]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [17]:
#Divide the dataset into dependent and independent features
X = data.drop("Exited",axis=1) #We are dropping the "Exited" column from the dataset and storing it in the variable x. This is because we want to predict the "Exited" column and we don't want to use it as a feature.
y = data["Exited"] #We are storing the "Exited" column in the variable y
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) #We are splitting the dataset into training and testing sets. test_size=0.2 means that we are using 20% of the dataset for testing and 80% for training. random_state=42 is used to get the same random numbers every time we run the code.
#Scale these features 
scaler = StandardScaler() #We are creating an object of the StandardScaler class. This class is used to scale the features of the dataset. It will standardize the features by removing the mean and scaling to unit variance.
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) #We are using the transform method to scale the test set. We are not using the fit_transform method because we don't want to fit the scaler to the test set. We want to use the same scaler that we used for the training set as the we dont want test set to influence the scaling of the training set. We want to use the same scaler that we used for the training set to scale the test set. This is because we want to use the same scaling for both the training and test sets. If we fit the scaler to the test set, it will influence the scaling of the training set and we don't want that. We want to use the same scaling for both the training and test sets.

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [19]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [20]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

#### ANN Implementation Steps
1. Sequential Neural Network
2. Dense ---> Hidden Nodes
3. Activation Functions ---> (Sigmoid, Tanh, Relu, Leaky Relu) in hidden Nodes , (Sigmoid, Softmax) in final Output
4. Optimizers ---> Backpropogation ---> Updating the Weights
5. Loss function
6. Metrics like [accuracy], [mse,mae]
7. Training Logs ---> Folder ---> Tensorboard ---> Visualization

In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [22]:
X_train.shape[1]

12

In [24]:
##Build our ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #HL1 We are adding a dense layer with 64 neurons and relu activation function. input_shape is the shape of the input data. It is the number of features in the dataset.
    Dense(32, activation='relu'), #HL2 We are adding a dense layer with 32 neurons and relu activation function.
    Dense(1, activation='sigmoid') #OL We are adding a dense layer with 1 neuron and sigmoid activation function. This is because we are doing binary classification and we want the output to be between 0 and 1.
])

c:\Users\hp\OneDrive\Desktop\Udemy\GenerativeAI\EndtoEnd_ANN_Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
import tensorflow as tf
opt = tf.keras.optimizers.Adam(learning_rate=0.001) #We are using the Adam optimizer with a learning rate of 0.001. The Adam optimizer is an adaptive learning rate optimization algorithm that is designed to handle sparse gradients on noisy problems. It is a combination of the best properties of the AdaGrad and RMSProp algorithms to provide an optimization algorithm that can handle sparse gradients on noisy problems.
losses = tf.keras.losses.BinaryCrossentropy() #We are using the binary crossentropy loss function. This is because we are doing binary classification and we want to minimize the difference between the predicted and actual values. The binary crossentropy loss function is used to measure the performance of a classification model whose output is a probability value between 0 and 1. It is used to calculate the loss for binary classification problems.
model.compile(optimizer=opt, loss=losses, metrics=['accuracy']) #We are compiling the model with the Adam optimizer and binary crossentropy loss function. We are also using accuracy as a metric to evaluate the performance of the model. The compile method is used to configure the model for training. It takes in the optimizer, loss function, and metrics as arguments.

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [27]:
##Set up the TensorBoard
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") #We are creating a directory to store the logs for TensorBoard. We are using the current date and time to create a unique directory name.
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1) #We are creating a callback for TensorBoard. We are passing the log directory and histogram frequency as arguments. histogram_freq=1 means that we are going to log the histograms of the weights and biases of the model after every epoch.

In [29]:
#Set up Early Stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True) #We are creating a callback for early stopping. We are passing the monitor, patience, and restore_best_weights as arguments. monitor='val_loss' means that we are going to monitor the validation loss. patience=5 means that we are going to wait for 5 epochs before stopping the training if the validation loss does not improve. restore_best_weights=True means that we are going to restore the best weights of the model after stopping the training.

In [30]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=[tensorflow_callback, early_stopping]) #We are training the model with the training set. We are using 20% of the training set for validation. We are training the model for 100 epochs and using a batch size of 32. We are also passing the callbacks for TensorBoard and early stopping as arguments.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8056 - loss: 0.4539 - val_accuracy: 0.8300 - val_loss: 0.3908
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8422 - loss: 0.3826 - val_accuracy: 0.8495 - val_loss: 0.3563
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8534 - loss: 0.3551 - val_accuracy: 0.8595 - val_loss: 0.3456
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8569 - loss: 0.3448 - val_accuracy: 0.8555 - val_loss: 0.3463
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8614 - loss: 0.3411 - val_accuracy: 0.8595 - val_loss: 0.3404
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3380 - val_accuracy: 0.8630 - val_loss: 0.3384
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8622 - loss: 0.3355 - val_accuracy: 0.8625 - val_loss: 0.3416
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8622 - loss: 0.3321 - val_accuracy: 0.8605 - val_loss: 0.3402
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3307 - val_accuracy: 0.8645 - val_loss: 0.3372
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.3295 - val_accuracy: 0.8630 - val_loss: 0.3339
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8655 - loss: 0.3256 - val_accuracy: 0.8645 - val_loss: 0.3367
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8696 - loss: 0.3230 - val_accuracy: 0.8625 - val_loss: 0.3448
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3221 - val_accuracy: 0.8615 - val_loss: 0.3385
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8665 - loss: 0.3203 - val_accuracy: 0.8620 - val_loss: 0.3377
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3190 - val_accuracy: 0.8660 - val_loss: 0.3359
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8662 - loss: 0.3176 - val_accuracy: 0.8665 - val_loss: 0.3331
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8685 - loss: 0.3152 - val_accuracy: 0.8650 - val_loss: 0.3340
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3138 - val_accuracy: 0.8570 - val_loss: 0.3453
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8704 - loss: 0.3138 - val_accuracy: 0.8620 - val_loss: 0.3361
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3112 - val_accuracy: 0.8645 - val_loss: 0.3337
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8710 - loss: 0.3105 - val_accuracy: 0.8635 - val_loss: 0.3356
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8710 - loss: 0.3090 - val_accuracy: 0.8655 - val_loss: 0.3350
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8705 - loss: 0.3075 - val_accuracy: 0.8645 - val_loss: 0.3365
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8734 - loss: 0.3070 - val_accuracy: 0.8645 - val_loss: 0.3362
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8739 - loss: 0.3045 - val_accuracy: 0.8645 - val_loss: 0.3417
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3031 - val_accuracy: 0.8645 - val_loss: 0.3374

In [31]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [32]:
## Load TensorBoard Extension
%load_ext tensorboard

In [38]:
%tensorboard --logdir logs/fit20260806-191442

Reusing TensorBoard on port 6006 (pid 26684), started 0:03:02 ago. (Use '!kill 26684' to kill it.)

In [40]:
!taskkill /PID 26684 /F

SUCCESS: The process with PID 26684 has been terminated.